name: typeCheck
on:
  pull_request:
    paths:
      - src/**/*
jobs:
  typeCheck:
    name: typeCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: using node
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.1
      - name: module install
        run: npm ci
      - name: run typeChecking
        run: npm run typeCheck
